allowBuilds:
  # post-install script is only needed for legacy npm versions and can be disabled for modern versions
  # https://github.com/unrs/unrs-resolver/issues/193#issuecomment-4397843323
  unrs-resolver: false

overrides:
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/47
  # Looks like it was related to its use of the tar package
  "@tootallnate/once": "^3.0.1"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/32
  brace-expansion: "^5.0.5"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/44
  lodash: "^4.18.1"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/42
  picomatch: "^4.0.4"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/40
  serialize-javascript: "^7.0.5"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/45
  ip-address: ">=10.1.1"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/54
  shell-quote: ">=1.8.4"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/56
  js-yaml: ">=4.2.0"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/57
  tar: ">=7.5.16"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/55
  "@babel/core": "^7.29.6"