allowBuilds:
  # post-install script is only needed for legacy npm versions and can be disabled for modern versions
  # https://github.com/unrs/unrs-resolver/issues/193#issuecomment-4397843323
  unrs-resolver: false

minimumReleaseAgeExclude:
  - tsdown@0.22.13

overrides:
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/59
  brace-expansion: "^5.0.7"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/42
  picomatch: "^4.0.4"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/72
  js-yaml: "^4.3.1"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/58
  sigstore: "^5.0.0"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/66
  "tar": "^7.5.18"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/62
  "shell-quote": "^1.9.0"
  # https://github.com/DecimalTurn/toml-patch/security/dependabot/71
  "postcss": "^8.5.23"