import { Value, NodeType, TreeNode, CST, InlineTable, Table, TableArray, KeyValue } from './cst';
import { last, blank, isDate, has } from './utils';
import ParseError from './parse-error';
import { IntegersAsBigInt } from './parse-options';
import { LocalDate, LocalTime, LocalDateTime, OffsetDateTime } from './date-format';

function integerFromRaw(raw: string, mode: IntegersAsBigInt = 'asNeeded'): number | bigint {
  const compact = raw.replace(/_/g, '');
  let normalized = compact;

  if (/^[+-]?0x/i.test(compact) || /^[+-]?0o/i.test(compact) || /^[+-]?0b/i.test(compact)) {
    const sign = compact[0] === '+' || compact[0] === '-' ? compact[0] : '';
    const body = compact.slice(sign ? 1 : 0);
    normalized = sign + body.toLowerCase();
  }

  let big: bigint | undefined;
  try {
    big = BigInt(normalized);
  } catch {
    // Some integer-valued JS numbers can be stringified in scientific notation
    // (e.g. "5e+22"). BigInt cannot parse that syntax, so preserve behavior
    // by coercing back to Number instead of throwing.
    return Number(compact);
  }

  if (mode === true) {
    return big;
  }
  if (mode === false) {
    return Number(big);
  }
  // 'asNeeded': return number when safe, bigint otherwise
  if (big >= BigInt(Number.MIN_SAFE_INTEGER) && big <= BigInt(Number.MAX_SAFE_INTEGER)) {
    return Number(big);
  }
  return big;
}

/**
 * Recursively tracks all nested inline tables within an inline table.
 * This ensures that nested inline tables like { nest = {} } are also tracked as immutable.
 */
function trackNestedInlineTables(inlineTable: InlineTable, basePath: string[], inlineTables: Set<string>) {
  for (const item of inlineTable.items) {
    const keyValue = item.item;
    
    if (keyValue.value.type === NodeType.InlineTable) {
      // Only allocate concat array when we actually have a nested inline table
      const fullPath = basePath.concat(keyValue.key.value);
      inlineTables.add(joinKey(fullPath));
      // Recursively track nested inline tables
      trackNestedInlineTables(keyValue.value, fullPath, inlineTables);
    }
  }
}

/**
 * Converts a custom Date subclass value to the corresponding Temporal object.
 * Does NOT check for Temporal availability — callers must guard that.
 */
function dateValueToTemporal(value: Date): any {
  // If the value is already a Temporal object (e.g. from a CST generated by
  // parseJS with Temporal input), return it directly — no conversion needed.
  if (value.constructor?.name?.startsWith?.('Temporal.') ||
      value.constructor?.name === 'PlainDate' ||
      value.constructor?.name === 'PlainTime' ||
      value.constructor?.name === 'PlainDateTime' ||
      value.constructor?.name === 'ZonedDateTime') {
    return value;
  }

  const T = (globalThis as any).Temporal;
  // LocalDate → Temporal.PlainDate
  if (value instanceof LocalDate) {
    return T.PlainDate.from(value.toISOString());
  }
  // LocalTime → Temporal.PlainTime
  if (value instanceof LocalTime) {
    return T.PlainTime.from(value.toISOString());
  }
  // LocalDateTime → Temporal.PlainDateTime
  if (value instanceof LocalDateTime) {
    return T.PlainDateTime.from(value.toISOString());
  }
  // OffsetDateTime → Temporal.ZonedDateTime
  if (value instanceof OffsetDateTime) {
    const iso = value.toISOString();
    // Extract offset: e.g. "2024-01-15T10:30:00+05:30" or "2024-01-15T10:30:00Z"
    const offsetMatch = iso.match(/([+-]\d{2}:\d{2}|Z)$/);
    const offset = offsetMatch ? offsetMatch[1] : 'Z';
    // Strip offset suffix to get the plain datetime
    const plainIso = iso.replace(/([+-]\d{2}:\d{2}|Z)$/, '');
    // ZonedDateTime.from requires an IANA timezone, not just an offset.
    // For a plain offset, we use the offset itself as the timezone annotation,
    // except for Z/UTC which must be "UTC".
    const tz = offset === 'Z' ? 'UTC' : offset;
    return T.ZonedDateTime.from(`${plainIso}${offset}[${tz}]`);
  }
  // Fallback: native Date or unrecognized Date subclass → Temporal.PlainDateTime
  return T.PlainDateTime.from(value.toISOString().replace('Z', ''));
}

/**
 * Converts the given CST to a JavaScript object.
 * 
 * @param cst The Concrete Syntax Tree to convert.
 * @param input The original input string (used for error reporting).
 * @param integersAsBigInt Controls integer representation.
 * @param temporal When true, date/time values are returned as Temporal objects.
 * @returns The JavaScript object representation of the CST.
 */
export default function toJS(
  cst: CST,
  input: string = '',
  integersAsBigInt: IntegersAsBigInt = 'asNeeded',
  temporal: boolean = false
): any {
  const result = blank();
  const tables: Set<string> = new Set();
  const table_arrays: Set<string> = new Set();
  const defined: Set<string> = new Set();
  const implicit_tables: Set<string> = new Set();
  const inline_tables: Set<string> = new Set();
  let active: any = result;
  let active_path: string[] = [];

  const state = { tables, table_arrays, defined, implicit_tables, inline_tables };

  // Specialized inline walk — only visits Table, TableArray, and KeyValue.
  // Skips Comment, Key, Value sub-nodes entirely (toValue handles InlineTable/
  // InlineArray recursively). This avoids the overhead of the generic traverse
  // dispatching through every CST node.
  for (const block of cst) {
    switch (block.type) {
      case NodeType.Table:
        handleTable(block as Table);
        for (const item of (block as Table).items) {
          if (item.type === NodeType.KeyValue) handleKeyValue(item as KeyValue);
        }
        break;

      case NodeType.TableArray:
        handleTableArray(block as TableArray);
        for (const item of (block as TableArray).items) {
          if (item.type === NodeType.KeyValue) handleKeyValue(item as KeyValue);
        }
        break;

      case NodeType.KeyValue:
        handleKeyValue(block as KeyValue);
        break;

      // Skip Comments
    }
  }

  return result;

  function handleTable(node: Table) {
    const key = node.key.item.value;
    try {
      validateKey(result, [], key, node.type, state);
    } catch (err) {
      const e = err as Error;
      throw new ParseError(input, node.key.loc.start, e.message);
    }

    const joined_key = joinKey(key);
    tables.add(joined_key);
    defined.add(joined_key);

    active = ensureTable(result, key);
    active_path = key;
  }

  function handleTableArray(node: TableArray) {
    const key = node.key.item.value;

    try {
      validateKey(result, [], key, node.type, state);
    } catch (err) {
      const e = err as Error;
      throw new ParseError(input, node.key.loc.start, e.message);
    }

    const joined_key = joinKey(key);
    table_arrays.add(joined_key);
    defined.add(joined_key);

    active = ensureTableArray(result, key);
    active_path = key;
  }

  function handleKeyValue(node: KeyValue) {
    const key = node.key.value;
    try {
      validateKey(active, active_path, key, node.type, state);
    } catch (err) {
      const e = err as Error;
      throw new ParseError(input, node.key.loc.start, e.message);
    }

    // Track implicit tables created by dotted keys.
    if (key.length > 1) {
      for (let i = 1; i < key.length; i++) {
        const implicit = joinKey(active_path.concat(key.slice(0, i)));
        implicit_tables.add(implicit);
        defined.add(implicit);
      }
    }

    let value;
    try {
      value = toValue(node.value, integersAsBigInt, temporal);
    } catch (err) {
      const e = err as Error;
      throw new ParseError(input, node.value.loc.start, e.message);
    }
    
    // Inline tables are immutable in TOML
    if (node.value.type === NodeType.InlineTable) {
      const base_path = active_path.concat(key);
      inline_tables.add(joinKey(base_path));
      trackNestedInlineTables(node.value, base_path, inline_tables);
    }
    const target = key.length > 1 ? ensureTable(active, key.slice(0, -1)) : active;

    target[last(key)!] = value;
    defined.add(joinKey(active_path.concat(key)));
  }
}

/**
 * Converts a TOML CST value node to a JavaScript value.
 * @param node The TOML CST value node.
 * @returns The corresponding JavaScript value.
 */
export function toValue(
  node: Value,
  integersAsBigInt: IntegersAsBigInt = 'asNeeded',
  temporal: boolean = false
): any {
  switch (node.type) {
    case NodeType.InlineTable:
      const result = blank();
      const defined_keys = new Set<string>();
      const defined_prefixes = new Map<string, string>(); // prefix -> one of the full keys that uses it

      node.items.forEach(({ item }) => {
        const key = item.key.value;
        const value = toValue(item.value, integersAsBigInt, temporal);

        // Check for duplicate keys and conflicting key paths
        const full_key = joinKey(key);
        
        // Check if this exact key was already defined
        if (defined_keys.has(full_key)) {
          throw new Error(`Duplicate key "${full_key}" in inline table`);
        }
        
        // Check if any prefix of this key conflicts with an existing key
        // e.g., if "a.b" is defined, we can't later define "a.b.c" (would overwrite the value)
        for (let i = 1; i < key.length; i++) {
          const prefix = joinKey(key.slice(0, i));
          if (defined_keys.has(prefix)) {
            throw new Error(`Key "${full_key}" conflicts with key: "${prefix}"`);
          }
        }
        
        // Check if this key is a prefix of an already defined key
        // e.g., if "a.b.c" is defined, we can't later define "a.b" (would overwrite the table)
        if (defined_prefixes.has(full_key)) {
          const existing = defined_prefixes.get(full_key)!;
          throw new Error(`Key "${full_key}" conflicts with key: "${existing}"`);
        }
        
        defined_keys.add(full_key);
        
        // Track all prefixes of this key
        for (let i = 1; i < key.length; i++) {
          const prefix = joinKey(key.slice(0, i));
          if (!defined_prefixes.has(prefix)) {
            defined_prefixes.set(prefix, full_key);
          }
        }

        const target = key.length > 1 ? ensureTable(result, key.slice(0, -1)) : result;
        target[last(key)!] = value;
      });

      return result;

    case NodeType.InlineArray:
      return node.items.map(item => toValue(item.item as Value, integersAsBigInt, temporal));

    case NodeType.DateTime:
      if (temporal) {
        if (typeof (globalThis as any).Temporal === 'undefined') {
          throw new Error(
            'Temporal API is not available in this runtime. ' +
            'Set temporal: false or use a runtime with Temporal support.'
          );
        }
        return dateValueToTemporal(node.value);
      }
      // Preserve TOML date/time custom classes so format is retained when
      // round-tripping through stringify() (e.g. date-only, time-only, local vs offset).
      // These classes extend Date, so JS users can still treat them as Dates.
      return node.value;

    case NodeType.String:
      return node.value;

    case NodeType.Integer:
      return integerFromRaw(node.raw, integersAsBigInt);

    case NodeType.Float:
    case NodeType.Boolean:
      return node.value;

    default:
      throw new Error(`Unrecognized value type "${(node as TreeNode).type}"`);
  }
}

function validateKey(
  object: any,
  prefix: string[],
  key: string[],
  type: NodeType.Table | NodeType.TableArray | NodeType.KeyValue,
  state: {
    tables: Set<string>;
    table_arrays: Set<string>;
    defined: Set<string>;
    implicit_tables: Set<string>;
    inline_tables: Set<string>;
  }
) {
  // Pre-compute all candidate key strings incrementally to avoid repeated
  // prefix.concat(key.slice(0, i)) + join allocations.
  // candidates[i] = joinKey(prefix.concat(key.slice(0, i + 1)))
  const prefixStr = prefix.length > 0 ? joinKey(prefix) : '';
  const candidates: string[] = new Array(key.length);
  let running = prefixStr;
  for (let i = 0; i < key.length; i++) {
    running = running ? running + '.' + key[i] : key[i];
    candidates[i] = running;
  }
  const joined_full_key = candidates[key.length - 1];

  // 0. Inline tables are immutable.
  // Once a key is assigned an inline table, it cannot be extended by dotted keys or table headers.
  // (toml-test invalid: spec-1.1.0/common-49-0, inline-table/overwrite-02, inline-table/overwrite-05)
  if (type === NodeType.KeyValue && key.length > 1) {
    for (let i = 1; i < key.length; i++) {
      const candidate = candidates[i - 1];
      if (state.inline_tables.has(candidate)) {
        throw new Error(`Cannot extend inline table at ${candidate}`);
      }
    }
  }
  
  // Also check if a table header tries to extend an inline table
  if ((type === NodeType.Table || type === NodeType.TableArray) && state.inline_tables.has(joined_full_key)) {
    throw new Error(`Cannot extend inline table at ${joined_full_key}`);
  }
  
  // Check if table header path contains an inline table
  if (type === NodeType.Table || type === NodeType.TableArray) {
    for (let i = 1; i < key.length; i++) {
      const candidate = candidates[i - 1];
      if (state.inline_tables.has(candidate)) {
        throw new Error(`Cannot extend inline table at ${candidate}`);
      }
    }
  }

  // 0a. Dotted key-value assignments cannot traverse into an Array of Tables.
  // This would be ambiguous (which element?) and is rejected by toml-test's
  // append-with-dotted-keys fixtures.
  if (type === NodeType.KeyValue && key.length > 1) {
    for (let i = 1; i < key.length; i++) {
      const candidate = candidates[i - 1];
      if (state.table_arrays.has(candidate)) {
        throw new Error(`Cannot traverse Array of Tables at ${candidate}`);
      }
    }
  }

  // 0b. Tables created implicitly by dotted keys cannot be re-opened via table headers.
  // (toml-test invalid: spec-1.1.0/common-46-0 and common-46-1)
  if ((type === NodeType.Table || type === NodeType.TableArray) && state.implicit_tables.has(joined_full_key)) {
    throw new Error(`Implicit table already defined: ${joined_full_key}`);
  }

  // 0c. A table path cannot later be re-assigned as a value.
  // Example: `type.name = "Nail"` then `type = { edible = false }` is invalid.
  // Example: `a.b.c = 1` then `a.b = 2` is invalid (a.b was implicitly created as a table).
  // (toml-test invalid: spec-1.1.0/common-50-0, table/append-with-dotted-keys-05)
  if (type === NodeType.KeyValue && state.implicit_tables.has(joined_full_key)) {
    throw new Error(`Table already defined: ${joined_full_key}`);
  }

  // 0d. Dotted keys cannot extend tables that were explicitly defined earlier.
  // Example: `[a.b.c]` followed by `[a]` then `b.c.t = "value"` is invalid.
  // (toml-test invalid: table/append-with-dotted-keys-01, table/append-with-dotted-keys-02)
  if (type === NodeType.KeyValue && key.length > 1) {
    for (let i = 1; i <= key.length; i++) {
      const candidate = candidates[i - 1];
      if (state.tables.has(candidate)) {
        throw new Error(`Cannot extend explicit table ${candidate} with dotted keys`);
      }
    }
  }

  // 1. Cannot override primitive value
  let index = 0;
  for (const part of key) {
    if (!has(object, part)) return;
    if (isPrimitive(object[part])) {
      throw new Error(`Value already defined for ${candidates[index]}`);
    }

    const joined_parts = candidates[index];
    if (Array.isArray(object[part]) && !state.table_arrays.has(joined_parts)) {
      throw new Error(`Cannot add to static array at ${joined_parts}`);
    }

    const next_is_last = index++ < key.length - 1;
    object = Array.isArray(object[part]) && next_is_last ? last(object[part]) : object[part];
  }

  const joined_key = joined_full_key;

  // 2. Cannot override table
  if (object && type === NodeType.Table && state.defined.has(joined_key)) {
    throw new Error(`Table already defined: ${joined_key}`);
  }

  // 2b. Cannot assign a value to a path that is already a table (explicit or implicit).
  if (object && type === NodeType.KeyValue && key.length === 1 && state.defined.has(joined_key)) {
    // If the path exists as a structured value, overriding it is invalid.
    if (!isPrimitive(object)) {
      throw new Error(`Table already defined: ${joined_key}`);
    }
  }

  // 3. Cannot add table array to static array or table
  if (object && type === NodeType.TableArray && !state.table_arrays.has(joined_key)) {
    throw new Error(`Cannot add Array of Tables to table at ${joined_key}`);
  }
}

function ensureTable(object: any, key: string[]): any {
  const target = ensure(object, key.slice(0, -1));
  const last_key = last(key)!;
  if (!target[last_key]) {
    target[last_key] = blank();
  }

  return target[last_key];
}

function ensureTableArray(object: any, key: string[]): any {
  const target = ensure(object, key.slice(0, -1));
  const last_key = last(key)!;
  if (!target[last_key]) {
    target[last_key] = [];
  }

  const next = blank();
  target[last(key)!].push(next);

  return next;
}

function ensure(object: any, keys: string[]): any {
  return keys.reduce((active, subkey) => {
    if (!active[subkey]) {
      active[subkey] = blank();
    }
    return Array.isArray(active[subkey]) ? last(active[subkey]) : active[subkey];
  }, object);
}

function isPrimitive(value: any) {
  return typeof value !== 'object' && !isDate(value);
}

function joinKey(key: string[]): string {
  return key.join('.');
}
