name: Benchmarks
on: 
  workflow_dispatch:

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22.x
    # Protection Against Supply Chain Attacks: https://socket.dev/blog/introducing-socket-firewall
    - uses: socketdev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
      with:
        mode: firewall
        firewall-version: latest # or use a pinned version (see releases)
    - name: Install
      run: sfw npm install
      env:
        CI: true
    - name: Build
      run: npm run build
    - name: Full Benchmark Suite
      run: npm run benchmark
    - name: Upload benchmark results