# Auth: Trusted Publishing: https://docs.npmjs.com/trusted-publishers

name: Publish Package

on:
  workflow_dispatch:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

jobs:

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # Might be used by jsr for authentication purposes
    steps:

      - name: Checkout
        uses: actions/checkout@v6
        with:
          submodules: true

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24.x
          registry-url: 'https://registry.npmjs.org/'

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          run_install: false

      - name: Install
        run: pnpm install --frozen-lockfile
        env:
          CI: true

      - name: Typecheck
        run: pnpm run typecheck

      - name: Build
        run: pnpm run build
        continue-on-error: true

      - name: Check git status
        run: git status && git diff

      - name: Publish to jsr
        run: npx -y jsr publish
        if: success() || steps.npm-publish.outcome == 'failure'
