name: Test and Build
on: 
  push:
    branches:
      - latest
      - master
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: 22.x
    # Protection Against Supply Chain Attacks: https://socket.dev/blog/introducing-socket-firewall
    - uses: socketdev/action@4337a545deecc20f19a909e52db7a2f6ba292f42 # v1.2.0
      with:
        mode: firewall
        firewall-version: latest # or use a pinned version (see releases)
    - name: Install
      run: sfw npm install
      env:
        CI: true
    - name: Typecheck
      run: npm run typecheck
    - name: Test
      run: npm test
    - name: Specs
      run: npm run specs
    - name: Build
      run: npm run build
    - name: Benchmark
      run: npm run benchmark -- --example
    - name: Create build artifacts
      uses: actions/upload-artifact@v4
      with: 
        path: dist/
        name: dist
        
