name: Test and Build
on: 
  push:
    branches:
      - latest
      - master
      - dev
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
      with:
        submodules: true
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
    - uses: socketdev/action@0a8642c1a20cd548c5e7e7632d115b683a4f5a24 # v1.1.5
      with:
        mode: firewall
        firewall-version: latest # or use a pinned version (see releases)
    - name: Install
      run: npm install
      env:
        CI: true
    - name: Typecheck
      run: sfw npm run typecheck
    - name: Test
      run: npm test
    - name: Specs
      run: npm run specs
    - name: Build
      run: npm run build
    - name: Benchmark
      run: npm run benchmark -- --example
    - name: Create build artifacts
      uses: actions/upload-artifact@v4
      with: 
        path: dist/
        name: dist
        
